[package]
name = "router"
version = "0.1.0"
authors = ["Tony <plutonyium@gmail.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces



[dependencies]
snafu = { version = "0.7.1" }
serde = { version = "1.0.114", default-features = false, features = [
  "derive",
  "alloc"
] }
schemars = "0.8.1"
cosmwasm-std = { version = "1.0.0", package = "secret-cosmwasm-std" , features=["iterator"]}
cosmwasm-storage = { version = "1.0.0", package = "secret-cosmwasm-storage" , features=["iterator"]}
shadeswap-shared = {  version = "0.1.0", path = "../../../packages/shadeswap_shared", features = []  }
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = [] }
[dev-dependencies]
cosmwasm-schema = { git = "https://github.com/CosmWasm/cosmwasm"}
secret-multi-test = { git = "https://github.com/securesecrets/secret-plus-utils", version = "0.13.4", features=["iterator"] }
