[package]
name = "credit-agency"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.4.0"
lending-utils = { version = "0.1.0", path = "../../../packages/lending_utils" }
lend-token = { version = "0.1.0", path = "../token" }
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = [
  "snip20",
  "storage_plus",
] }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1"
query_auth = { path = "../../query_auth" }

[dev-dependencies]
anyhow = "1"
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = ["multi-test"] }
shade-multi-test = { version = "0.1.0", path = "../../../packages/multi_test", features = [ "snip20"] }
